### ISSUE TITLE
not receiving all the results that I should

### ISSUE THREAD

**Issue by gehadza** [mark-watson/java_practical_semantic_web#2]
Hello,

By using this code to query the Lookup DBpedia service I am not receiving all the results that I should. For instance, quering Lookup service from my browser like this: http://lookup.dbpedia.org/api/search.asmx/KeywordSearch?QueryClass=&QueryString=Renewable%20energy

I am receiving Renewable energy,Plug-in hybrid,Emissions trading,Sustainable energy,Renewable resource. Instead, programmatically I receive just "renewable energy" and "sustainable energy".

Can you help me with this?
Thank you in advance

**Comment by mark-watson** [comment]
You might want to look at the text of the response when the dbpedia lookup code is called.

Look for:
   sax.parse(ins, this);

and instead of passing the input stream `ins` to the XML parser, print it out and see if all the results are present. Perhaps some results are not getting parsed correctly?
